on:
  pull_request:

env:
  CARGO_TERM_COLOR: always

jobs:
  rust:
    runs-on: ubuntu-latest

    env:
      PRIVATE_KEY: ${{ secrets.MetricsPrivateKey }}
      FROM: ${{ github.event.pull_request.base.sha }}
      TO: ${{ github.event.pull_request.head.sha }}
      REPO: ${{ github.repository }}
      ISSUE_NUMBER: ${{ github.event.pull_request.number }}
      TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
    - uses: actions/checkout@v3

    - name: Test
      run: cargo test

    - name: Upload metrics
      run: ./upload.sh

    - name: Diff metrics
      run: python3 ./diff.py